# laravel_suivi/render.yaml

services:
  - type: web
    name: meditrack-laravel
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_NAME
        value: MediTrack
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://meditrack-laravel.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.xxxxxx
      - key: DB_PASSWORD
        value: votre_mot_de_passe