applications:
  app:
    type: php:8.2
    build:
      flavor: composer
    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"
    hooks:
      build: |
        composer install --no-dev --optimize-autoloader